import './AbridgeNotePanel.css';
import { NOTE_TEXT, NOTE_HIGHLIGHTS, CLARIFICATION_RESPONSE } from '../data/mockCase';
import type { NoteHighlight } from '../data/mockCase';

type Props = {
  hasClarification: boolean;
  onPhraseClick: (sourceId: string, excerpt?: string) => void;
};

type Segment = { text: string; highlight?: NoteHighlight };

function buildSegments(text: string, globalOffset: number, highlights: NoteHighlight[]): Segment[] {
  const relevant = highlights
    .filter((h) => h.start < globalOffset + text.length && h.end > globalOffset)
    .map((h) => ({
      ...h,
      localStart: Math.max(0, h.start - globalOffset),
      localEnd: Math.min(text.length, h.end - globalOffset),
    }))
    .sort((a, b) => a.localStart - b.localStart);

  const segments: Segment[] = [];
  let cursor = 0;

  for (const h of relevant) {
    if (h.localStart > cursor) {
      segments.push({ text: text.slice(cursor, h.localStart) });
    }
    segments.push({ text: text.slice(h.localStart, h.localEnd), highlight: h });
    cursor = h.localEnd;
  }

  if (cursor < text.length) {
    segments.push({ text: text.slice(cursor) });
  }

  return segments;
}

function Noteparagraph({
  text,
  globalOffset,
  highlights,
  onPhraseClick,
}: {
  text: string;
  globalOffset: number;
  highlights: NoteHighlight[];
  onPhraseClick: (sourceId: string, excerpt?: string) => void;
}) {
  const segments = buildSegments(text, globalOffset, highlights);

  return (
    <p className="note-text">
      {segments.map((seg, i) =>
        seg.highlight ? (
          <button
            key={i}
            className={`note-highlight note-highlight--${seg.highlight.criterionId.toLowerCase()}`}
            onClick={() => onPhraseClick(seg.highlight!.sourceId, seg.text)}
            title={seg.highlight.label}
          >
            {seg.text}
            <span className="note-highlight-indicator" aria-hidden>
              {seg.highlight.criterionId}
            </span>
          </button>
        ) : (
          <span key={i}>{seg.text}</span>
        )
      )}
    </p>
  );
}

export default function AbridgeNotePanel({ hasClarification, onPhraseClick }: Props) {
  const paragraphs = NOTE_TEXT.split('\n\n');
  let offset = 0;

  return (
    <div className="abridge-panel panel">
      <div className="panel-header">
        <div className="abridge-header-left">
          <div className="abridge-logo">
            <span className="abridge-logo-a">A</span>
            <span className="abridge-logo-text">bridge</span>
          </div>
          <div>
            <div className="abridge-title">Encounter Note</div>
            <div className="abridge-subtitle">Draft · AI Generated · 07/18/2026 · SYNTHETIC</div>
          </div>
        </div>
        <div className="abridge-header-chips">
          <span className="chip chip-purple">AI Generated</span>
          <span className="chip chip-blue">Linked Evidence</span>
        </div>
      </div>

      <div className="note-body">
        <div className="note-highlight-legend">
          <span className="legend-label">Highlighted =</span>
          <span className="legend-item legend-item--criteria">evidence cited by AuthLens</span>
          <span className="legend-sep">·</span>
          <span className="legend-hint">click to view source</span>
        </div>

        {paragraphs.map((para, i) => {
          const go = offset;
          offset += para.length + 2; // +2 for '\n\n'
          return (
            <Noteparagraph
              key={i}
              text={para}
              globalOffset={go}
              highlights={NOTE_HIGHLIGHTS}
              onPhraseClick={onPhraseClick}
            />
          );
        })}

        {hasClarification && (
          <section className="note-section note-section--clarification animate-fade-in">
            <div className="note-section-label">
              <span className="clarification-badge">Clinician Clarification Added — clar-001</span>
            </div>
            <p className="note-text note-clarification-text">{CLARIFICATION_RESPONSE}</p>
          </section>
        )}

        <div className="note-footer">
          <span className="note-footer-item">Generated by Abridge AI</span>
          <span className="note-footer-sep">·</span>
          <span className="note-footer-item">Requires clinician attestation</span>
          <span className="note-footer-sep">·</span>
          <span className="note-footer-item highlight-hint">
            Highlighted phrases = evidence cited by AuthLens
          </span>
        </div>
      </div>
    </div>
  );
}
