import './DisclosurePanel.css';
import { DISCLOSURE_DECISIONS } from '../data/mockCase';

type Props = {
  onSourceClick: (sourceId: string) => void;
};

export default function DisclosurePanel({ onSourceClick }: Props) {
  const included = DISCLOSURE_DECISIONS.filter((d) => d.decision === 'include');
  const excluded = DISCLOSURE_DECISIONS.filter((d) => d.decision === 'exclude');

  return (
    <div className="disclosure-panel panel">
      <div className="panel-header">
        <div className="disc-header-left">
          <span className="panel-header-title">Disclosure Review</span>
          <span className="disc-policy-ref">Minimum-necessary disclosure · MHP-IMG-2201</span>
        </div>
        <div className="disc-summary-chips">
          <span className="chip chip-met">{included.length} included</span>
          <span className="chip chip-missing">{excluded.length} excluded</span>
        </div>
      </div>

      <div className="disc-body">
        <p className="disc-intro">
          AuthLens reviewed all chart items and applied minimum-necessary disclosure rules. Only
          items directly relevant to the lumbar MRI prior authorization are included in the packet.
        </p>

        <section className="disc-section">
          <div className="disc-section-title disc-section-title--include">
            Included ({included.length})
          </div>
          {included.map((d) => (
            <div key={d.decision_id} className="disc-item disc-item--include">
              <div className="disc-item-icon">✓</div>
              <div className="disc-item-body">
                <button
                  className="disc-item-title"
                  onClick={() => onSourceClick(d.source_id)}
                  title="View source"
                >
                  {d.item_description}
                  <span className="disc-source-id">{d.source_id}</span>
                </button>
                <div className="disc-item-reason">{d.reason}</div>
              </div>
            </div>
          ))}
        </section>

        <section className="disc-section">
          <div className="disc-section-title disc-section-title--exclude">
            Excluded ({excluded.length})
          </div>
          {excluded.map((d) => (
            <div key={d.decision_id} className="disc-item disc-item--exclude">
              <div className="disc-item-icon disc-item-icon--exclude">✕</div>
              <div className="disc-item-body">
                <button
                  className="disc-item-title disc-item-title--exclude"
                  onClick={() => onSourceClick(d.source_id)}
                  title="View source"
                >
                  {d.item_description}
                  <span className="disc-source-id">{d.source_id}</span>
                </button>
                <div className="disc-item-reason">{d.reason}</div>
                {d.phi_category && (
                  <span className="disc-phi-tag">phi_category: {d.phi_category}</span>
                )}
              </div>
            </div>
          ))}
        </section>

        <div className="disc-footer-note">
          <span>ℹ</span> Disclosure decisions are generated by AuthLens and must be reviewed by a
          clinician before submission. AuthLens does not auto-submit.
        </div>
      </div>
    </div>
  );
}
