import './PriorAuthFormDraft.css';
import { ASSESSMENTS } from '../data/mockCase';
import type {
  ApiCase,
  ApiCriterionAssessment,
  ApiFormDraft,
  ApiChartItem,
} from '../api/client';

type Props = {
  hasClarification: boolean;
  onSourceClick: (sourceId: string, excerpt?: string) => void;
  caseData?: ApiCase;
  formDraft?: ApiFormDraft;
  assessments?: ApiCriterionAssessment[];
};

const STATUS_LABEL: Record<string, string> = {
  met: 'Met',
  weak: 'Needs clarification',
  missing: 'Not documented',
  conflicting: 'Conflicting',
  not_applicable: 'Not applicable',
};

const HISTORY_LABEL: Record<string, string> = {
  condition: 'Condition',
  medication: 'Medication',
  procedure: 'Procedure',
  referral: 'Referral',
  observation: 'Exam / observation',
  other: 'Other',
};
// Categories that represent clinical history/background (not the requested order).
const HISTORY_CATEGORIES = new Set(['condition', 'medication', 'procedure', 'referral', 'observation', 'other']);

const ATTESTATION_FALLBACK =
  'DRAFT FOR CLINICIAN REVIEW — generated by AuthLens from cited chart evidence approved for ' +
  'disclosure. Not sent to any payer; this system has no way to send it. Not a guarantee of ' +
  'approval. A licensed clinician must review, correct, and attest before any submission.';

function fmtDate(iso?: string): string {
  if (!iso) return '—';
  // birth_date is already YYYY-MM-DD; timestamps are ISO.
  return iso.slice(0, 10);
}

function cleanName(name: string): string {
  // The mock form drafter can double-append "(synthetic)"; collapse it.
  return name.replace(/(\s*\(synthetic\))+/gi, '').trim() + ' (synthetic)';
}

export default function PriorAuthFormDraft({
  hasClarification,
  onSourceClick,
  caseData,
  formDraft,
  assessments: liveAssessments,
}: Props) {
  const activeAssessments = caseData?.assessments ?? liveAssessments ?? (ASSESSMENTS as unknown as ApiCriterionAssessment[]);
  const form = caseData?.form_draft ?? formDraft ?? null;
  const ready = !!form || caseData?.status === 'ready_for_review' || caseData?.status === 'verified';

  const payerName = caseData?.policy.payer_name ?? 'Meridian Health Plans (fictional)';
  const formName = form?.payer_form_name ?? 'Advanced Imaging Prior Authorization Request';
  const policyId = caseData?.policy.policy_id ?? 'MHP-IMG-2201';
  const attestation = form?.attestation ?? ATTESTATION_FALLBACK;

  // Patient / service / indication straight from the case.
  const patient = caseData?.patient;
  const service = caseData?.requested_service;
  const indication = caseData?.clinical_indication;
  const codes = caseData?.indication_codes ?? [];

  // Disclosure decisions drive the minimum-necessary boundary.
  const excluded = new Set(
    (caseData?.disclosure_decisions ?? [])
      .filter((d) => d.decision === 'exclude')
      .map((d) => d.source_id),
  );
  const excludedCount = excluded.size;

  // Relevant clinical history = included chart history items (not the order).
  const history: ApiChartItem[] = (patient?.chart_items ?? []).filter(
    (c) => HISTORY_CATEGORIES.has(c.category) && !excluded.has(c.source_id),
  );

  // Criterion checklist with the documented finding text (from form fields).
  const fieldByCrit = new Map<string, string>();
  for (const f of form?.fields ?? []) {
    const m = f.field_id.match(/^f-crit-(.+)$/);
    if (m) fieldByCrit.set(m[1], f.value);
  }
  const criteria = activeAssessments.map((a) => {
    const status = caseData || liveAssessments
      ? a.status
      : (hasClarification ? (a as any).status_after ?? a.status : a.status);
    const evidence = (a.evidence && a.evidence.length ? a.evidence : (a as any).evidence_after) ?? [];
    return {
      id: a.criterion_id,
      status,
      summary: fieldByCrit.get(a.criterion_id) ?? (a as any).rationale ?? '',
      sourceId: evidence[0]?.source_id as string | undefined,
      excerpt: evidence[0]?.excerpt as string | undefined,
    };
  });

  const openGaps = criteria.filter((c) => c.status === 'missing' || c.status === 'weak' || c.status === 'conflicting');
  const hasOpenGap = !ready && openGaps.length > 0;

  return (
    <div className="pa-paper">
      {/* Letterhead */}
      <header className="pa-letterhead">
        <div className="pa-letterhead-main">
          <div className="pa-payer">{payerName}</div>
          <div className="pa-form-title">{formName}</div>
          <div className="pa-form-sub">Utilization Management · Medical Necessity Policy {policyId}</div>
        </div>
        <div className="pa-letterhead-side">
          <span className="pa-mock-stamp">MOCK · SYNTHETIC</span>
          <div className="pa-form-no">Form UM-72148</div>
          <div className="pa-form-date">Prepared 07/18/2026</div>
        </div>
      </header>

      <div className={`pa-status-strip ${ready ? 'pa-status-ready' : 'pa-status-draft'}`}>
        <span className="pa-status-dot" />
        {ready
          ? 'READY FOR CLINICIAN REVIEW — not submitted'
          : 'DRAFT — clarification pending; not submitted'}
      </div>

      {hasOpenGap && (
        <div className="pa-gap-warning">
          ⚠ {openGaps.map((g) => g.id).join(', ')} still require clinician clarification before this
          request is complete.
        </div>
      )}

      <div className="pa-paper-body">
        {/* Section A — Patient */}
        <section className="pa-section">
          <div className="pa-section-head">A · Patient Information</div>
          <div className="pa-field-grid">
            <FormLine label="Patient name" value={patient ? cleanName(patient.display_name) : '—'} />
            <FormLine label="Date of birth" value={fmtDate(patient?.birth_date)} />
            <FormLine label="Sex" value={patient?.sex ?? '—'} />
            <FormLine label="Patient identifier" value={patient?.patient_id ?? '—'} />
          </div>
        </section>

        {/* Section B — Requested service */}
        <section className="pa-section">
          <div className="pa-section-head">B · Requested Service / Procedure</div>
          <div className="pa-field-grid">
            <FormLine label="Service" value={service?.service_name ?? '—'} wide />
            <FormLine label="Procedure code" value={service ? `${service.code_system} ${service.code}` : '—'} />
            <FormLine label="Modality" value={service?.modality ?? '—'} />
            <FormLine label="Body site" value={service?.body_site ?? '—'} />
          </div>
        </section>

        {/* Section C — Diagnosis / indication */}
        <section className="pa-section">
          <div className="pa-section-head">C · Diagnosis &amp; Clinical Indication</div>
          <div className="pa-field-grid">
            <FormLine label="Clinical indication" value={indication ?? '—'} wide />
            <FormLine label="Diagnosis code(s)" value={codes.length ? codes.join(', ') : '—'} />
          </div>
        </section>

        {/* Section D — Relevant clinical history (prior history) */}
        <section className="pa-section">
          <div className="pa-section-head">D · Relevant Clinical History</div>
          {history.length === 0 ? (
            <div className="pa-empty">No relevant prior history disclosed.</div>
          ) : (
            <table className="pa-history-table">
              <tbody>
                {history.map((h) => (
                  <tr key={h.source_id}>
                    <td className="pa-hist-cat">{HISTORY_LABEL[h.category] ?? h.category}</td>
                    <td className="pa-hist-desc">
                      <span className="pa-hist-display">{h.display}</span>
                      {h.detail && <span className="pa-hist-detail"> — {h.detail}</span>}
                    </td>
                    <td className="pa-hist-cite">
                      <button className="pa-cite-btn" title="View source" onClick={() => onSourceClick(h.source_id)}>↗</button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
          {excludedCount > 0 && (
            <div className="pa-history-note">
              {excludedCount} unrelated item{excludedCount > 1 ? 's' : ''} withheld under the
              minimum-necessary standard.
            </div>
          )}
        </section>

        {/* Section E — Medical necessity criteria */}
        <section className="pa-section">
          <div className="pa-section-head">E · Medical-Necessity Criteria ({policyId})</div>
          <div className="pa-criteria-list">
            {criteria.map((c) => {
              const met = c.status === 'met';
              return (
                <div key={c.id} className={`pa-crit pa-crit--${c.status}`}>
                  <div className="pa-crit-box">{met ? '☑' : '☐'}</div>
                  <div className="pa-crit-main">
                    <div className="pa-crit-top">
                      <span className="pa-crit-id">{c.id}</span>
                      <span className={`pa-crit-status pa-crit-status--${c.status}`}>
                        {STATUS_LABEL[c.status] ?? c.status}
                      </span>
                    </div>
                    {c.summary && <div className="pa-crit-summary">{c.summary}</div>}
                  </div>
                  {c.sourceId && (
                    <button
                      className="pa-cite-btn"
                      title="View cited source"
                      onClick={() => onSourceClick(c.sourceId!, c.excerpt)}
                    >↗</button>
                  )}
                </div>
              );
            })}
          </div>
        </section>

        {/* Section F — Attestation & signature */}
        <section className="pa-section pa-section--attest">
          <div className="pa-section-head">F · Attestation</div>
          <p className="pa-attestation-text">{attestation}</p>
          <div className="pa-signature-row">
            <div className="pa-sign-line">
              <span className="pa-sign-rule" />
              <span className="pa-sign-caption">Clinician signature</span>
            </div>
            <div className="pa-sign-line pa-sign-line--date">
              <span className="pa-sign-rule" />
              <span className="pa-sign-caption">Date</span>
            </div>
          </div>
          <div className="pa-nosubmit">
            AuthLens has no submission capability. A licensed clinician must review, correct, and
            submit this request outside AuthLens.
          </div>
        </section>
      </div>
    </div>
  );
}

function FormLine({ label, value, wide }: { label: string; value: string; wide?: boolean }) {
  return (
    <div className={`pa-line${wide ? ' pa-line--wide' : ''}`}>
      <div className="pa-line-label">{label}</div>
      <div className="pa-line-value">{value}</div>
    </div>
  );
}
