"""Mock payer form drafter (implements the FormDrafter port).

Hard gate: drafting accepts only the typed, VERIFIED packet together with
its passing VerificationResult (or, via ``draft_by_id``, the verified
packet id stored on the case). It raises for anything else — there is no
code path from unverified or free-form text to the form, and no submit
action of any kind. Field values are drawn from packet claims; the drafter
never composes new clinical statements.
"""

from datetime import datetime, timezone

from app.contracts import (
    AuthLensCase,
    ClaimType,
    FormDraftField,
    PacketStatus,
    PriorAuthorizationFormDraft,
    PriorAuthorizationPacket,
    VerificationResult,
    VerificationSeverity,
)

ATTESTATION_TEXT = (
    "DRAFT FOR CLINICIAN REVIEW — generated by AuthLens from cited chart "
    "evidence approved for disclosure. Not sent to any payer; this system "
    "has no way to send it. Not a guarantee of approval. A licensed "
    "clinician must review, correct, and approve every field before any "
    "use outside AuthLens."
)

MOCK_PAYER_FORM_NAME = "Meridian Health Plans — Prior Authorization Request (MOCK)"


class FormDraftError(RuntimeError):
    """Base error for form drafting."""


class UnverifiedPacketError(FormDraftError):
    """Raised when the input is not a verified packet with passing verification."""


class MockPayerFormDrafter:
    """Populates the synthetic payer form from verified packet claims only."""

    def draft(
        self,
        packet: PriorAuthorizationPacket,
        verification: VerificationResult,
        case: AuthLensCase,
    ) -> PriorAuthorizationFormDraft:
        """Return the mock form draft, or raise if the packet is not verified."""
        if not isinstance(packet, PriorAuthorizationPacket) or not isinstance(
            verification, VerificationResult
        ):
            raise UnverifiedPacketError(
                "Form drafting accepts only the typed verified packet and its "
                "verification result — never free-form text."
            )
        if packet.status is not PacketStatus.VERIFIED:
            raise UnverifiedPacketError(
                f"Packet {packet.packet_id} has status {packet.status.value!r}; "
                "only a VERIFIED packet can be drafted into a form."
            )
        if verification.packet_id != packet.packet_id:
            raise UnverifiedPacketError(
                f"Verification {verification.verification_id} covers packet "
                f"{verification.packet_id}, not {packet.packet_id}."
            )
        if not verification.passed or any(
            i.severity is VerificationSeverity.BLOCKING for i in verification.issues
        ):
            raise UnverifiedPacketError(
                f"Verification for packet {packet.packet_id} did not pass; "
                "blocking issues prevent form drafting."
            )
        if packet.case_id != case.case_id:
            raise FormDraftError(
                f"Packet {packet.packet_id} belongs to case {packet.case_id}, "
                f"not {case.case_id}."
            )

        fields = self._build_fields(packet, verification, case)
        return PriorAuthorizationFormDraft(
            form_id=f"form-{case.case_id}",
            case_id=case.case_id,
            packet_id=packet.packet_id,
            payer_form_name=MOCK_PAYER_FORM_NAME,
            fields=fields,
            attestation=ATTESTATION_TEXT,
            status="ready_for_review",
            generated_at=datetime.now(timezone.utc),
        )

    def draft_by_id(
        self, case: AuthLensCase, packet_id: str
    ) -> PriorAuthorizationFormDraft:
        """Draft from the verified packet id stored on the case."""
        if case.packet is None or case.verification is None:
            raise UnverifiedPacketError(
                f"Case {case.case_id} has no verified packet on record."
            )
        if case.packet.packet_id != packet_id:
            raise UnverifiedPacketError(
                f"Packet {packet_id} is not the packet on record for case "
                f"{case.case_id}."
            )
        return self.draft(case.packet, case.verification, case)

    def _build_fields(
        self,
        packet: PriorAuthorizationPacket,
        verification: VerificationResult,
        case: AuthLensCase,
    ) -> list[FormDraftField]:
        fields = [
            FormDraftField(
                field_id="f-patient",
                label="Patient name",
                value=f"{case.patient.display_name} (synthetic)"
                if case.synthetic
                else case.patient.display_name,
                source_claim_ids=[],
            ),
            FormDraftField(
                field_id="f-dob",
                label="Date of birth",
                value=case.patient.birth_date,
                source_claim_ids=[],
            ),
            FormDraftField(
                field_id="f-member",
                label="Patient identifier",
                value=case.patient.patient_id,
                source_claim_ids=[],
            ),
            FormDraftField(
                field_id="f-service",
                label="Requested service",
                value=(
                    f"{case.requested_service.service_name} "
                    f"({case.requested_service.code_system} {case.requested_service.code})"
                ),
                source_claim_ids=[],
            ),
            FormDraftField(
                field_id="f-indication",
                label="Clinical indication (clinician-stated)",
                value=case.clinical_indication
                + (
                    f" ({', '.join(case.indication_codes)})"
                    if case.indication_codes
                    else ""
                ),
                source_claim_ids=[],
            ),
        ]

        labels = {c.criterion_id: c.label for c in case.criteria}
        for criterion in case.criteria:
            claims = [
                c
                for c in packet.claims
                if c.claim_type is ClaimType.CLINICAL
                and c.criterion_id == criterion.criterion_id
            ]
            if not claims:
                continue
            fields.append(
                FormDraftField(
                    field_id=f"f-crit-{criterion.criterion_id}",
                    label=labels[criterion.criterion_id],
                    value=" ".join(c.text for c in claims),
                    source_claim_ids=[c.claim_id for c in claims],
                )
            )

        unresolved = [
            i
            for i in verification.issues
            if i.severity in (VerificationSeverity.WARNING, VerificationSeverity.INFO)
        ]
        if unresolved:
            fields.append(
                FormDraftField(
                    field_id="f-warnings",
                    label="Unresolved reviewer warnings",
                    value=" | ".join(i.description for i in unresolved),
                    source_claim_ids=sorted(
                        {i.claim_id for i in unresolved if i.claim_id}
                    ),
                )
            )
        return fields
